# Generated by Django 3.2.7 on 2021-09-07 14:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('census_admin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.TextField()),
                ('done', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Support Messages',
                'db_table': 'Support Messages',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(default='auth/app-assets/img/profile.png', null=True, upload_to='auth/app-assets/img/profile_pics/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg'))])),
                ('lastName', models.CharField(max_length=30)),
                ('firstName', models.CharField(max_length=30)),
                ('otherName', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=30)),
                ('gender', models.CharField(blank=True, max_length=15)),
                ('religion', models.CharField(max_length=20)),
                ('family_size', models.CharField(max_length=3)),
                ('dob', models.DateField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('lga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_lga', to='census_admin.lga')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Profile',
                'db_table': 'User Profile',
            },
        ),
    ]
